### ISSUE TITLE
fix font for syndrom oszusta

### ISSUE THREAD

**Issue by ErdaradunGaztea** [ErdaradunGaztea/GenderDysphoria.fyi#3]
Add css rule that says sth like:

```css
html[lang=pl] .markup blockquote {
  font-family: "some nice font", serif;
}
```
